name: Deploy Vite Game to LAMP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Vite project
      - name: Build Vite project
        run: npm run build

      # 5. Prepare files for upload
      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          cp -r dist/* deploy/

      # 6. Upload deploy folder contents to LAMP
      - name: Upload site files
        uses: appleboy/scp-action@master
        with:
          host: lamp.ms.wits.ac.za
          username: ${{ secrets.LAMP_USER }}
          key: ${{ secrets.LAMP_SSH_KEY }}
          port: 22
          source: "deploy/*"
          target: "/home/${{ secrets.LAMP_USER }}/public_html/"

      # 7. Fix permissions on LAMP server
      - name: Fix permissions
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: lamp.ms.wits.ac.za
          username: ${{ secrets.LAMP_USER }}
          key: ${{ secrets.LAMP_SSH_KEY }}
          script: |
            find ~/public_html -type d -exec chmod 755 {} \;
            find ~/public_html -type f -exec chmod 644 {} \;
            echo "Permissions fixed and deployment complete!"

      # 8. Cleanup
      - name: Cleanup deploy folder
        run: rm -rf deploy
